CKV_AZURE_57
nimrodkor/checkov pull request #127
Opened 2021-03-16 11:22 UTC by hadarpl

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#cors
Ensure that CORS disallows every resource to access function apps

2021-03-16 15:29 UTC, nimrodkor requested changes

2021-03-16 15:29 UTC, nimrodkor commented on checkov/terraform/checks/resource/azure/AppServiceDisallowCORS.py
> +        return 'site_config/[0]/cors/[0]/allowed_origins'
@hadarpl Duplicate of #125 ?

2021-03-16 15:30 UTC, nimrodkor commented on checkov/terraform/checks/resource/azure/AppServiceDisallowCORS.py
> +        return 'site_config/[0]/cors/[0]/allowed_origins'
Oh, it's for app service. So same comment about the name

2021-03-17 10:13 UTC, hadarpl commented on checkov/terraform/checks/resource/azure/AppServiceDisallowCORS.py
> +        return 'site_config/[0]/cors/[0]/allowed_origins'
Fixed.

2021-03-17 14:43 UTC, nimrodkor approved these changes

2021-03-17 14:43 UTC, merged