added VMStorageOsDisk check and test
nimrodkor/checkov pull request #131
Opened 2021-03-16 12:45 UTC by avivgu

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-16 15:35 UTC, nimrodkor requested changes

2021-03-16 15:35 UTC, nimrodkor commented on checkov/terraform/checks/resource/azure/VMStorageOsDisk.py
> +        supported_resources = ['azurerm_virtual_machine']
@hadarpl This resource is deprecated
![image](https://user-images.githubusercontent.com/16308767/111336431-e7a02c00-867d-11eb-8068-0dddaafb44bc.png)

2021-03-16 15:35 UTC, nimrodkor commented on checkov/terraform/checks/resource/azure/VMStorageOsDisk.py
> +        return CheckResult.FAILED
@hadarpl I believe your logic is inverted, `vhd_uri` means this is an unmanaged disk:
![image](https://user-images.githubusercontent.com/16308767/111336534-01da0a00-867e-11eb-9e2c-304e0cdaf8e7.png)

2021-03-16 15:44 UTC, avivgu commented on checkov/terraform/checks/resource/azure/VMStorageOsDisk.py
> +        supported_resources = ['azurerm_virtual_machine']
so we don't want this check?

2021-03-16 17:26 UTC, nimrodkor commented on checkov/terraform/checks/resource/azure/VMStorageOsDisk.py
> +        supported_resources = ['azurerm_virtual_machine']
We want it, just on different resource types. They are listed in the image I attached

2021-03-17 08:47 UTC, avivgu commented on checkov/terraform/checks/resource/azure/VMStorageOsDisk.py
> +        supported_resources = ['azurerm_virtual_machine']
Done

2021-03-17 08:47 UTC, avivgu commented on checkov/terraform/checks/resource/azure/VMStorageOsDisk.py
> +        return CheckResult.FAILED
Done

2021-03-17 14:42 UTC, nimrodkor approved these changes

2021-03-17 14:42 UTC, merged