CKV_AZURE_129
nimrodkor/checkov pull request #179
Opened 2021-03-17 15:02 UTC by milkanas

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-18 12:25 UTC, rotemavni requested changes

2021-03-18 12:25 UTC, rotemavni commented on checkov/terraform/checks/resource/azure/MariaDBGeoBackupEnabled.py
> +        if 'geo_redundant_backup_enabled' not in conf:
@milkanas Classic case of `BaseResourceValueCheck`

2021-03-21 16:11 UTC, rotemavni requested changes

2021-03-21 16:11 UTC, rotemavni commented on tests/terraform/checks/resource/azure/test_MariaDBGeoBackupEnabled.py
> +    def test_failure(self):
@milkanas Please add a test case for when the key doesn't exist

2021-03-22 12:56 UTC, nimrodkor approved these changes

2021-03-22 12:56 UTC, merged