added check + UT
nimrodkor/checkov pull request #9
Opened 2021-03-09 11:06 UTC by livnoni

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-09 12:24 UTC, livnoni commented
I was mixing between 2 checks, i close it for now

2021-03-09 15:12 UTC, rotemavni commented on tests/terraform/runner/test_plan_runner.py
> +        self.assertEqual(62, report.get_summary()["failed"])
@livnoni Why is this changed?

2021-03-09 15:12 UTC, nimrodkor requested changes
@livnoni see my comments

2021-03-09 15:12 UTC, nimrodkor commented on checkov/terraform/checks/resource/aws/APIGatewayKeyRotation.py
> +class APIGatewayKeyRotation(BaseResourceValueCheck):
@livnoni I believe the check name is false - this is KMSKey Rotation, not APIGateway Key rotation

2021-03-09 15:12 UTC, nimrodkor commented on tests/terraform/checks/resource/aws/test_APIGatewayCacheEnable.py
> +        resource_conf = {'rest_api_id': ['${example_id}']}
@livnoni please use the `hcl2.loads` test format / the load from dir, not the hardcoded conf values

2021-03-09 15:39 UTC, rotemavni commented on tests/terraform/runner/test_plan_runner.py
> +        self.assertEqual(62, report.get_summary()["failed"])
@livnoni nvm

2021-03-09 16:05 UTC, livnoni commented on tests/terraform/runner/test_plan_runner.py
> +        self.assertEqual(62, report.get_summary()["failed"])
because I added a new check, no?

2021-03-09 16:41 UTC, livnoni commented on checkov/terraform/checks/resource/aws/APIGatewayKeyRotation.py
> +class APIGatewayKeyRotation(BaseResourceValueCheck):
You right - my bad

2021-03-10 10:45 UTC, rotemavni approved these changes
@livnoni Please resolve conflicts and merge :)

2021-03-10 17:14 UTC, nimrodkor approved these changes

2021-03-10 17:26 UTC, merged